FROM node:latest

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ADD package.json /usr/src/app/package.json
RUN yarn install --silent
RUN yarn global add react-scripts@1.0.15 --silent

CMD ["yarn", "start"]