FROM node:latest

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ARG REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL

ADD package.json /usr/src/app/package.json
RUN yarn install --silent
RUN yarn global add pushstate-server --silent

ADD . /usr/src/app

RUN yarn run build

CMD ["pushstate-server", "build", "3000"]